version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:066959092968:task-definition/NewMathServiceTask:1"
        LoadBalancerInfo:
          ContainerName: "MathServiceContainer"
          ContainerPort: 8080